export const REQUEST_PRODUCT_LIST = "REQUEST_PRODUCT_LIST";
export const REQUEST_PRODUCT_SUCCES = "REQUEST_PRODUCT_SUCCES"
export const REQUEST_PRODUCT_FAIL = "REQUEST_PRODUCT_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"